name             'aar'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures aar'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'apt', '~> 3.0.0'
depends 'zipfile', '~> 0.1.0'
depends 'python', '~> 1.4.6'
depends 'database', '~> 4.0.9'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.3.4'
